<template>
    <div>
        <div id="statistics-container" style="width: 100%; border:5px solid #fff3cd; min-height: 200px;">
            <div v-if="group !== undefined" style="width: 50%; min-width: 1024px; margin-left: auto; margin-right: auto;">

                <h3>File info</h3>
                <b-table-simple fixed bordered small responsive>
                    <colgroup><col width="20%" align="right"></colgroup>
                    <b-thead head-variant="dark">
                    <b-tr>
                        <b-th>Aspect</b-th>
                        <b-th>Value</b-th>
                    </b-tr>
                    </b-thead>
                    <b-tbody>
                        <b-tr v-if="group.filename !== ''">
                            <b-td>Filename</b-td>
                            <b-td>{{group.filename}}</b-td>
                        </b-tr>
                        <b-tr v-if="group.title !== ''">
                            <b-td>Title</b-td>
                            <b-td>{{group.title}}</b-td>
                        </b-tr>
                        <b-tr v-if="group.description !== ''">
                            <b-td>Description</b-td>
                            <b-td>{{group.description}}</b-td>
                        </b-tr>
                        <b-tr>
                            <b-td>qlog version</b-td>
                            <b-td>{{group.version}}</b-td>
                        </b-tr>
                        <b-tr v-if="Object.keys(group.summary).length > 0">
                            <b-td>Summary</b-td>
                            <b-td>{{JSON.stringify(group.summary, null, 4)}}</b-td>
                        </b-tr>
                        <b-tr>
                            <b-td>Trace count</b-td>
                            <b-td>{{group.getConnections().filter( (c) => !c.wasAutoGenerated ).length}}</b-td>
                        </b-tr>
                        <b-tr>
                            <b-td>Total event count</b-td>
                            <b-td>{{totalEventCount}}</b-td>
                        </b-tr>
                    </b-tbody>
                </b-table-simple>
                
                <StatisticsConnectionRenderer v-if="totalEventCount > 0" v-for="(connection,index) in group.getConnections().filter( (c) => !c.wasAutoGenerated )" :key="'conn_' +index" :connection="connection" :index="index" />

            </div>
        </div>
    </div>
</template>

<style scoped>
    #toplevel > tr[role="row"] td:first-of-type {
        text-align: right;
        font-weight: bold;
        padding-right: 10px;
    }
</style>

<script lang="ts">
    import { Component, Vue, Prop, Watch } from "vue-property-decorator";
    import StatisticsConfig from "./data/StatisticsConfig";
    import * as qlog from '@/data/QlogSchema';

    import StatisticsConnectionRenderer from "@/components/stats/StatisticsConnectionRenderer.vue";

    @Component({
        components: {
            StatisticsConnectionRenderer,
        },
    })
    export default class StatisticsRenderer extends Vue {
        @Prop()
        public config!: StatisticsConfig;

        protected get group() {
            return this.config.group;
        }

        protected get totalEventCount() {
            if ( !this.config.group ) {
                return -1;
            }
                
            let output = 0;

            for ( const trace of this.config.group!.getConnections() ){
                if ( !trace.wasAutoGenerated ) {
                    output += trace.getEvents().length;
                }
            }

            return output;
        }

        protected get qlogns(){
            return qlog;
        }
    }

</script>
